Test commit to try and track down a tricky race condition during parallel builds. In particular when all cores are busy, we run into failures during buildkernel missing the x86/endian.h file.
This patch is to attempt to make ${_ILINKS} run before genoffset.o

--- genoffset.o ---
cc -target x86_64-unknown-freebsd13.0 --sysroot=/wrkdirs/usr/ports/os/buildkernel/work-zol/wrkdirs/usr/ports/os/buildkernel/work-zol/src/amd64.amd64/tmp -B/wrkdir
s/usr/ports/os/buildkernel/work-zol/wrkdirs/usr/ports/os/buildkernel/work-zol/src/amd64.amd64/tmp/usr/bin -c -O2 -pipe -fno-strict-aliasing -g -nostdinc -I. -I/wr
kdirs/usr/ports/os/buildkernel/work-zol/src/sys -I/wrkdirs/usr/ports/os/buildkernel/work-zol/src/sys/contrib/ck/include -I/wrkdirs/usr/ports/os/buildkernel/work-z
ol/src/sys/contrib/libfdt -D_KERNEL -DHAVE_KERNEL_OPTION_HEADERS -include opt_global.h -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -MD -MF.depend.genoffs
et.o -MTgenoffset.o -fdebug-prefix-map=./machine=/wrkdirs/usr/ports/os/buildkernel/work-zol/src/sys/amd64/include -fdebug-prefix-map=./x86=/wrkdirs/usr/ports/os/b
uildkernel/work-zol/src/sys/x86/include -mcmodel=kernel -mno-red-zone -mno-mmx -mno-sse -msoft-float -fno-asynchronous-unwind-tables -ffreestanding -fwrapv -fstac
k-protector -gdwarf-2 -Wall -Wredundant-decls -Wnested-externs -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wundef -Wno-pointer-sign -D__
printf__=__freebsd_kprintf__ -Wmissing-include-dirs -fdiagnostics-show-option -Wno-unknown-pragmas -Wno-error-tautological-compare -Wno-error-empty-body -Wno-erro
r-parentheses-equality -Wno-error-unused-function -Wno-error-pointer-sign -Wno-error-shift-negative-value -Wno-address-of-packed-member -mno-aes -mno-avx -std=iso
9899:1999 /wrkdirs/usr/ports/os/buildkernel/work-zol/src/sys/kern/genoffset.c
In file included from /wrkdirs/usr/ports/os/buildkernel/work-zol/src/sys/kern/genoffset.c:35:
In file included from /wrkdirs/usr/ports/os/buildkernel/work-zol/src/sys/sys/param.h:98:
In file included from /wrkdirs/usr/ports/os/buildkernel/work-zol/src/sys/sys/types.h:46:
./machine/endian.h:6:10: fatal error: 'x86/endian.h' file not found